[tool.setuptools.packages.find]
where = ["."]
include = ["autoemx", "autoemx.*", "autoemxsp", "autoemxsp.*"]
exclude = ["paper_data", "examples", "tests"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autoemx"
version = "1.0.3"
description = "AutoEMX - Automated Electron Microscopy X-Ray Spectroscopy for Compositional Characterization of Materials"
readme = "README.md"
keywords = [
    "SEM",
    "EDS",
    "EDX",
    "composition",
    "microscopy",
    "spectroscopy"
]
license = "LicenseRef-AcademicNonCommercial"
license-files = ["LICENSE.txt"]
authors = [
    { name = "Andrea Giunto", email = "agiunto@lbl.gov" }
]
requires-python = ">=3.11,<3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "cvxpy>=1.5.3,<=1.7.3",
    "ecos>=2.0.12",
    "lmfit>=1.3.2,<=1.3.4",
    "matplotlib>=3.5.2,<=3.10.6",
    "numpy>=1.26.4,<=2.2.6",
    "pandas>=2.2.2,<=2.3.3",
    "pydantic>=2.7.0,<=2.11.3",
    "pymatgen>=2024.11.13,<=2025.10.7",
    "scikit-learn>=1.5.1,<=1.7.2",
    "scikit-image>=0.24.0,<=0.25.2",
    "scipy>=1.14.1,<=1.16.2",
    "seaborn>=0.13.2,<=0.13.2",
    "sympy>=1.13.2,<=1.14.0",
    "yellowbrick==1.5",
    "opencv-python>=4.10.0,<=4.12.0.88",
    "pillow>=10.0.1"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
]